# Configuration file for Ansible TinyLlama Integration

# LLM Settings
[llm]
model_name = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
quantization = "4bit"  # Options: null, "4bit", "8bit"
max_tokens = 1024
temperature = 0.7

# API Settings
[api]
host = "127.0.0.1"
port = 8000
debug = false

# Ansible Settings
[ansible]
callback_plugins_path = "./src/ansible_plugins/callbacks"
library_path = "./src/ansible_plugins/modules"
filter_plugins_path = "./src/ansible_plugins/filters"

# Windows SSH Settings
[windows_ssh]
default_user = "Administrator"
default_port = 22
enable_key_auth = true

# Logging Settings
[logging]
level = "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
file = "./logs/ansible_llm.log"
max_file_size_mb = 10
backup_count = 5
