---
# System Information Tasks
# Collects and displays system information

- name: Gather system information
  ansible.builtin.debug:
    msg: "Collecting system information for {{ ansible_hostname }}"

- name: Get kernel information
  ansible.builtin.command: uname -r
  register: kernel_info
  changed_when: false

- name: Show kernel version
  ansible.builtin.debug:
    var: kernel_info.stdout

- name: Get distribution information
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"

- name: Check disk usage
  ansible.builtin.command: df -h
  register: disk_usage
  changed_when: false

- name: Show disk usage
  ansible.builtin.debug:
    var: disk_usage.stdout_lines

- name: Get memory information
  ansible.builtin.command: free -h
  register: memory_info
  changed_when: false

- name: Show memory information
  ansible.builtin.debug:
    var: memory_info.stdout_lines

- name: Get CPU information
  ansible.builtin.command: lscpu
  register: cpu_info
  changed_when: false

- name: Show CPU information
  ansible.builtin.debug:
    var: cpu_info.stdout_lines

- name: Create system report file
  ansible.builtin.copy:
    content: |
      SYSTEM REPORT
      =============
      Hostname: {{ ansible_hostname }}
      Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}
      Kernel: {{ kernel_info.stdout }}
      CPU: {{ ansible_processor[1] }}
      Memory: {{ ansible_memtotal_mb }} MB
      Date: {{ ansible_date_time.date }}
      Generated by: Ansible Linux Automation
    dest: /tmp/system_report.txt
    mode: '0644'

- name: Report created
  ansible.builtin.debug:
    msg: "System report created at /tmp/system_report.txt"
